site_name: Condenser
theme:
  name: material
  features:
    - content.action.edit
not_in_nav: |
  /stubs
  /assets
copyright: "UCL Advanced Research Computing, 2025"
site_description: "Documentation for the UCL Condenser Platform"
repo_url: https://github.com/UCL-ARC/condenser-mkdocs
edit_uri: edit/main/docs/
site_url: https://condenser.arc.ucl.ac.uk
plugins:
  - git-revision-date-localized
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list
