site_name: Condenser User Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Terms and Conditions: terms_and_conditions.md
  - About the Platform: about.md
  - Developer Guide:
    - Getting Started: developer_guide/getting_started.md
    - Deploying with the Rancher GUI: developer_guide/deploying_rancher.md
    - Deploying with Terraform: developer_guide/deploying_terraform.md
    - Deploying with Kubernetes: developer_guide/deploying_kubernetes.md
    - Configuring a VM for web ingress: developer_guide/ingress.md
    - Example Deployments: developer_guide/examples.md
  - End User Guide:
    - Accessing a VM by SSH: end_user_guide/ssh.md
copyright: "UCL Advanced Research Computing, 2024"
site_description: "Documentation for the UCL Condenser Platform"
