site_name: Condenser User Documentation
theme: readthedocs
not_in_nav: |
  /stubs
copyright: "UCL Advanced Research Computing, 2024"
site_description: "Documentation for the UCL Condenser Platform"
repo_url: https://github.com/UCL-ARC/condenser-mkdocs
edit_uri: blob/main/docs/
site_url: https://docs.condenser.arc.ucl.ac.uk
