[project]
site_name = "Condenser documentation"
site_url = "https://condenser.arc.ucl.ac.uk"
site_description = "Documentation for Condenser, UCL's Private Cloud for Research"
site_author = "ARC Environments"
copyright = "UCL Advanced Research Computing, 2026"
edit_uri = "edit/main/docs/"
repo_url = "https://github.com/UCL-ARC/condenser-mkdocs"

[project.theme]
features = [
  "content.action.edit", # Edit this page
  "content.action.view"  # View source of this page
]
favicon = "assets/favicon.ico"
logo = "assets/UCL_social_icon_square_web.jpg"
