authors:
  cdkharris:
    name: Camilla Harris
    description: Senior Research Infrastructure Developer
    avatar: https://profiles.ucl.ac.uk/93790-camilla-harris/photo
    url: https://profiles.ucl.ac.uk/93790-camilla-harris
  ostrachan:
    name: Ollie Strachan
    description: Agile Delivery Manager
    avatar: ""
    url: ""
