name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - docs/**

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: automatic-release
      uses: softprops/action-gh-release@v2.2.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.tag.outputs.new_tag }}
        generate_release_notes: true
        prerelease: false
